Create Bootstrap_fail.montyp
Tried to bootstrap, but fail...
Error:  

if self.stack: raise SyntaxError("Missing 'end' for: " + ' > '.join(self.stack))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing 'end' for: def > if > def > def > def > if > if > if > if > def > def > if > def > if > if > if > if > if > if > if > if > if > if > if >